In [1]:
from sklearn.datasets import load_iris

iris = load_iris()

print("鸢尾花数据集：\n", iris)

鸢尾花数据集：
 {'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.

In [2]:
print(iris["DESCR"])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [3]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
print(iris.data,iris.data.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)
print(x_train,x_train.shape)

In [ ]:
from sklearn.feature_extraction import DictVectorizer

data = [{'city':'北京','temperate':100},{'city':'深圳','temperate':60},{'city':'上海','temperate':30}]

transfer = DictVectorizer(sparse=False)

data_new = transfer.fit_transform(data)

print(data_new)

In [ ]:
transfer.get_feature_names_out()

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

data = ["life is short, i like python","life is too long, i dislike python"]

transfer = CountVectorizer()

data_new = transfer.fit_transform(data)

print(data_new.toarray())

In [ ]:
transfer.get_feature_names_out()

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import jieba

data = ["生活很短，我喜欢生命","生活太长，我不喜欢生命"]

data_new = []

for sent in data:
    data_new.append("".join(list(jieba.cut(sent))))

transfer = CountVectorizer(stop_words=["生活太长",'生活很短'])

data_final = transfer.fit_transform(data_new)

print(data_final.toarray())
print(transfer.get_feature_names_out())

TfidfVectorizer

tfidf = tf(词频)*idf(逆向文档频率)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import jieba

data = ["生活很短，我喜欢生命","生活太长，我不喜欢生命"]

data_new = []

for sent in data:
    data_new.append("".join(list(jieba.cut(sent))))

transfer = TfidfVectorizer(stop_words=["生活太长",'生活很短'])

data_final = transfer.fit_transform(data_new)

print(data_final.toarray())
print(transfer.get_feature_names_out())

In [ ]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

iris = load_iris().data

df = pd.DataFrame(iris)

transfer = MinMaxScaler(feature_range=(1,2))

data = transfer.fit_transform(df)

print(data)

In [ ]:
from sklearn.preprocessing import StandardScaler

transfer = StandardScaler()

data = transfer.fit_transform(df)

print(data)

特征选择
Filter过滤式：
方差选择法（低方差特征过滤）
相关程度（高相关系数特征过滤）
Embedded嵌入式：
决策树
正则化
深度学习

In [ ]:
from sklearn.feature_selection import VarianceThreshold

transfer = VarianceThreshold(threshold=0.5)

data = transfer.fit_transform(df)

print(data)

In [ ]:
from scipy.stats import pearsonr

r = pearsonr(df[0],df[1])

print(r)

In [ ]:
from sklearn.decomposition import PCA

data = [[2,8,4,5],[6,3,0,8],[5,4,9,1]]

transfer = PCA(n_components=0.95)

data_new = transfer.fit_transform(data)

print(data_new)

In [1]:
import pandas as pd

aisles = pd.read_csv(r'aisles.csv')
order_products = pd.read_csv(r'order_products__prior.csv')
orders = pd.read_csv(r'orders.csv')
products = pd.read_csv(r'products.csv')

In [2]:
order_products.head()

order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [3]:
orders.head()

order_id  user_id eval_set  order_number  order_dow  order_hour_of_day  \
0   2539329        1    prior             1          2                  8   
1   2398795        1    prior             2          3                  7   
2    473747        1    prior             3          3                 12   
3   2254736        1    prior             4          4                  7   
4    431534        1    prior             5          4                 15   

   days_since_prior_order  
0                     NaN  
1                    15.0  
2                    21.0  
3                    29.0  
4                    28.0

In [4]:
products.head()

product_id                                       product_name  aisle_id  \
0           1                         Chocolate Sandwich Cookies        61   
1           2                                   All-Seasons Salt       104   
2           3               Robust Golden Unsweetened Oolong Tea        94   
3           4  Smart Ones Classic Favorites Mini Rigatoni Wit...        38   
4           5                          Green Chile Anytime Sauce         5   

   department_id  
0             19  
1             13  
2              7  
3              1  
4             13

In [5]:
aisles.head()

aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [10]:
tab1 = pd.merge(aisles,products,on=["aisle_id","aisle_id"])

In [11]:
tab2 = pd.merge(tab1,order_products,on=["product_id","product_id"])

In [12]:
tab3 = pd.merge(tab2,orders,on=["order_id","order_id"])

In [13]:
tab3

aisle_id                       aisle  product_id  \
0                1       prepared soups salads         209   
1                1       prepared soups salads       22853   
2                4               instant foods       12087   
3                4               instant foods       47570   
4               13              prepared meals       10089   
...            ...                         ...         ...   
32434484       134  specialty wines champagnes       47713   
32434485       134  specialty wines champagnes       49562   
32434486       134  specialty wines champagnes       49562   
32434487       134  specialty wines champagnes       49562   
32434488       134  specialty wines champagnes       49562   

                                      product_name  department_id  order_id  \
0                              Italian Pasta Salad             20     94246   
1                                Pesto Pasta Salad             20     94246   
2                 Chicken Flavor Ramen Noodle Soup              9     94246   
3         Original Flavor Macaroni & Cheese Dinner              9     94246   
4                                           Dolmas             20     94246   
...                                            ...            ...       ...   
32434484                            Sparkling Rose              5   3014872   
32434485             Blanc De Noirs Sparkling Wine              5     34570   
32434486             Blanc De Noirs Sparkling Wine              5    250923   
32434487             Blanc De Noirs Sparkling Wine              5   1319402   
32434488             Blanc De Noirs Sparkling Wine              5   2298986   

          add_to_cart_order  reordered  user_id eval_set  order_number  \
0                         5          0   114082    prior            26   
1                         4          0   114082    prior            26   
2                        15          0   114082    prior            26   
3                        14          1   114082    prior            26   
4                        25          0   114082    prior            26   
...                     ...        ...      ...      ...           ...   
32434484                  1          0    63218    prior             1   
32434485                  1          1    37901    prior            13   
32434486                  1          1    26431    prior            27   
32434487                  1          1    26431    prior            34   
32434488                  1          0    37901    prior             9   

          order_dow  order_hour_of_day  days_since_prior_order  
0                 0                 20                     1.0  
1                 0                 20                     1.0  
2                 0                 20                     1.0  
3                 0                 20                     1.0  
4                 0                 20                     1.0  
...             ...                ...                     ...  
32434484          1                 14                     NaN  
32434485          3                  9                    13.0  
32434486          5                 11                    10.0  
32434487          2                 14                     7.0  
32434488          2                 11                    13.0  

[32434489 rows x 14 columns]

In [14]:
table = pd.crosstab(tab3["user_id"],tab3["aisle"])

In [15]:
from sklearn.decomposition import PCA

transfer = PCA(n_components=0.95)

data = transfer.fit_transform(table)

data.shape

(206209, 44)

In [16]:
table.shape

(206209, 134)